version: '3'

services:
  db:
    image: postgres
    container_name: jamfhooks_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    container_name: jamfhooks_web
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "./wait-for-it.sh db:5432 -s -t 60 -- echo 'Database\ up'
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py makemigrations
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py collectstatic --no-input
      && cd jamf_webhook_connector
      && gunicorn jamf_webhook_connector.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/jamf_webhook_connector/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    container_name: jamfhooks_nginx
    volumes:
      - static_volume:/code/jamf_webhook_connector/static
    build: ./nginx
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - web
volumes:
  static_volume:
