version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: >
      bash -c "python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py makemigrations
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
