version: '3'

services:
  db:
    image: postgres
    container_name: jamfhooks_db
  web:
    container_name: jamfhooks_web
    build: .
    command: >
      bash -c "./wait-for-it.sh db:5432 -s -t 60 -- echo 'Database\ up'
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py makemigrations
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
