version: '3'

services:
  db:
    image: postgres
    container_name: jamfhooks_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/database:/var/lib/postgresql/data
  web:
    container_name: jamfhooks_web
    build: ./jamf_webhook_connector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/code
      - static_volume:/code/jamf_webhook_connector/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    container_name: jamfhooks_nginx
    volumes:
      - static_volume:/code/jamf_webhook_connector/static
    build: ./nginx
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - web
volumes:
  static_volume:
  data:
