version: '3'

services:
  db:
    image: postgres
    container_name: jamfhooks_db
  web:
    container_name: jamfhooks_web
    build: .
    command: >
      bash -c "./wait-for-it.sh db:5432 -s -t 60 -- echo 'Database\ up'
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py makemigrations
      && python jamf_webhook_connector/manage.py migrate
      && python jamf_webhook_connector/manage.py collectstatic --no-input
      && cd jamf_webhook_connector
      && gunicorn jamf_webhook_connector.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/jamf_webhook_connector/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    container_name: jamfhooks_nginx
    volumes:
      - static_volume:/code/jamf_webhook_connector/static
    build: ./nginx
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - web
    server:
        container_name: jamfhooks_sftp
        build:
            context: ./sftp
            args:
                SSH_MASTER_USER: ${SSH_MASTER_USER}
                SSH_MASTER_PASS: ${SSH_MASTER_PASS}
        hostname: sftp
        ports:
            - "2222:22"
        volumes:
            - ./uploads:/uploads
volumes:
  static_volume:
