# Generated by Django 2.1.5 on 2019-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf_webhook_receiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSSStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('JSSStartup', 'JSSShutdown'), ('JSSShutdown', 'JSSShutdown')], max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
