# Generated by Django 2.1.5 on 2019-01-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf_webhook_receiver', '0002_auto_20190114_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jssstatus',
            name='status',
            field=models.CharField(choices=[('JSSStartup', 'JSSStartup'), ('JSSShutdown', 'JSSShutdown')], max_length=11),
        ),
    ]
