# Generated by Django 2.1.5 on 2019-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf_webhook_receiver', '0003_auto_20190114_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('url', models.URLField(help_text='Your full JSS URL')),
                ('status', models.CharField(choices=[('JSSStartup', 'JSSStartup'), ('JSSShutdown', 'JSSShutdown')], max_length=11)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='JSSStatus',
        ),
    ]
