# Generated by Django 2.1.5 on 2019-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf_webhook_receiver', '0004_auto_20190118_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='jssserver',
            name='ComputerAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='ComputerCheckIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='ComputerInventoryCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='ComputerPatchPolicyCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='ComputerPolicyFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='ComputerPushCapabilityChanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='DeviceRateLimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='JSSShutdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='JSSStartup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='MobileDeviceCheckIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='MobileDeviceCommandCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='MobileDeviceEnrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='MobileDevicePushSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='MobileDeviceUnEnrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='PatchSoftwareTitleUpdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='PushSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='RestAPIOperation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='SCEPChallenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='SmartGroupComputerMembershipChange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jssserver',
            name='SmartGroupMobileDeviceMembershipChange',
            field=models.BooleanField(default=False),
        ),
    ]
